config/routes.rb
Rails.application.routes.draw do
  get 'gymplaces/index'

  get 'gymplaces/new'

  root 'home#landing'
  get '/about' => 'home#about'
  
  get '/login' =>'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  delete '/logout' => 'sessions#destroy'

  get '/posts' => 'posts#index'
  post '/posts' => 'posts#create'
  post '/posts' => 'posts#index'

  resources :gymplaces do
    resources :posts
  end
  resources :users
  
 
    

end

app/models/gymplace.rb
class Gymplace < ActiveRecord::Base
  has_many :posts
  has_many :users


  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200"} 
 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
 	belongs_to :gymplace
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :posts
    has_many :gymplaces
   
    
    has_secure_password
    
    validates_presence_of :password, :on => :create
  	validates_presence_of :email
  	validates_uniqueness_of :email
	
		has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #allows access in views
  helper_method :current_user
  
  before_filter :disable_nav, only: [:landing]
  
  def disable_nav
    @disable_nav = true
  end


  @gymplaces = Gymplace.all
  @hash = Gmaps4rails.build_markers(@users) do |user, marker|
  marker.lat user.latitude
  marker.lng user.longitude
end
  
  #method will log user in or return nil
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/gymplaces_controller.rb
class GymplacesController < ApplicationController
  # all gyms to display here with users post
  def index
    if current_user
  	@gymplaces = Gymplace.all.order("create_at DESC").paginate(page: params[:page], per_page: 4)
    @gymplace = Gymplace.where(post_id: current_user)
    end
  end

  def new
    @gymplace = Gymplace.new
  end

  def show
   @gymplace = Gymplace.find(params[:id])
    @gymplaces = current_user.gymplaces
    #changed @posts to be posts for the gym by all users
    #otherwise you are showing reviews for other gyms on the show page of the gym
    @posts = @gymplace.posts.order("created_at DESC").paginate(page: params[:page], per_page: 4)
    if current_user
      @post = @gymplace.posts.build
    end    
  end

  def create
    @gymplace = current_user.gymplaces.build(gymplaces_params)
    if @gymplace.save
      flash[:notice] = "Added"
      redirect_to current_user
    else
      flash[:alert] = "Not added"
      redirect_to :back 
    end
  end

  def edit
    @gymplace = Gymplace.find(params[:id])      
  end

  def update
    @gymplace = Gymplace.find(params[:id])
    if @gymplace.update_attributes(gymplaces_params)
      redirect_to  current_user
    end
  end

  def destroy
    session[:user_id] = nil
    @gymplace = Gymplace.find(params[:id])
    @gymplace.destroy
  end

private

  
  def gymplaces_params
      params.require(:gymplace).permit(:place, :description, :location, :city, :latitude, :zipcode, :email, :telephone ).merge(user_id: :curent_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 
  before_action :current_user
  
	def landing
		@disable_nav = true 
		if current_user
			@gymplaces = Gymplace.order("created_at DESC").paginate(page: params[:page], :per_page => 4)
    	@gymplace = Gymplace.where(post_id: current_user)
			@posts = Post.all.order("created_at DESC").paginate(page: params[:page], :per_page => 4)
		end
	end

	def about
		
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    #all posts to be display, new post to be created
    def index
        if session[:user_id]
            @posts = Post.all.order("create_at DESC").paginate(page: params[:page], :per_page => 4)
            @post = Post.where(post_id: current_user)
            redirect_to root_path
        else
            flash[:alert] = "You must be logged in to view GymTalk reviews."
            redirect_to login_path
        end
    end
    
    def new
        @post = Post.new
    end   
    
    def show
        @post = Post.find(params[:id])
        @posts = @current_user.posts
        redirect_to gymplace_path
    end

    def edit
        @post = Post.find(params[:id])
        redirect_to 'index'
    end
        
    
    def create 
        #find the gymplace from the url  
        @gymplace = Gymplace.find(params[:gymplace_id])
        #build a record for a post for that gymplace with the submitted info from form
        @post = @gymplace.posts.build(post_params)
        #add the user_id of the current user
        @post.user = current_user
        
        if @post.save
            redirect_to gymplace_path(@gymplace)
        else
            redirect_to :back
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
    end
    
    
    private
    
    def post_params
        params.require(:post). permit(:post)
    end
       
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
    
    end
    
    def create
        @user = User.find_by(username: params[:username])
        
        if @user && @user.authenticate(params[:password])
            flash[:notice] = "Welcome"
            session[:user_id] = @user.id
            redirect_to @user
        else
            flash.now[:alert] = "Your are not signed in."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end 


end    

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # all users will be displayed
  def index
    @users = User.all
  end
  
  
  #@user is new user instance
  def new
    @user = User.new
  end
  
  
  #create a new user w/params
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Your profile has been create."
        session[:user_id] = @user.id
      redirect_to user_path(@user) 
     else
       flash[:notice] = "No profile created."
       redirect_to :back
    end
  end
   
    # user is displayed by params
     def show
       @user = User.find(params[:id])
       @posts = current_user.posts
     end
     
    # editing user by params
    def edit
      @user = User.find(params[:id])
    end
    
    
    # def update
    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        redirect_to @user
      else
        redirect_to :back
      end 
    end
    
    
    # destroys a user 
    def destroy
      session[:user_id] = nil
      @user = User.find(params[:id])
      @user.destroy 
    end
    
        
      # parameters for
      private
      
      def user_params
        params.require(:user).permit(:fname, :lname, :username, :sex, :password, :email, :avatar)
      end
end
  
      
  

  
    

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current &crarr; 
      #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "&crarr; 
      asc") ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction,:page =>nil), {:class => css_class}
  end
end

app/helpers/gymplaces_helper.rb
module GymplacesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gymplaces/_gymplaceform.html.erb
<div id="signup">

        <div class="form-group">

                <%= form_for @gymplace do |f| %>


                <div class="control-group">
                        <%= f.label :Place, class: "control-label" %>
                
                        <%= f.text_field :place class: "form-control", placeholder: "name of place" %>
        
                </div><br>

                <div class="control-group">   
                        <%= f.label :Description, class: "control-label" %>
        
                        <%= f.text_field :description, class: "form-control", placeholder: "description, services" %>
                
                </div><br>

                <div class="control-group">  
                        <%= f.label :Location, class: "control-label" %>
                        <%= f.text_field :location, class: "form-control", placeholder: "address" %>
                </div><br>

                 <div class="control-group">  
                        <%= f.label :City, class: "control-label" %>
                        <%= f.text_field :city, class: "form-control", placeholder: "city" %>
                </div><br>

                <div class="control-group">       
                        <%= f.label :Latitude, class: "control-label" %> 
                        <%= f.latitude_field :latitude, class: "form-control", placeholder: "Password" %>
                </div><br>

                 <div class="control-group">       
                        <%= f.label :Long, class: "control-label" %>
                        <%= f.longitude_field :longitude, class: "form-control", placeholder: "longitude" %>
                </div><br>
                
                <div class="control-group">       
                        <%= f.label :Zipcode, class: "control-label" %> 
                        <%= f.text_field :zipcode, class: "form-control", placeholder: "zipcode" %>
                </div><br>

                <div class="control-group">       
                        <%= f.label :Tel, class: "control-label" %> 
                        <%= f.telephone_field :telephone, class: "form-control", placeholder: "telephone" %>
                </div><br>
                        <% end %>
        </div>
</div>

        

       

app/views/gymplaces/index.html.erb
<h1>GymTalk This Week</h1>

<ul>

<% @gymplaces.each do |p| %>
	<h2><%= link_to p.gymplace %></h2>
<% end %>
 
 <% if current_user %>

<div class="panel panel-default">
    <div class="panel-body-post">
    		<% @gymplaces.each do |p| %>

    		<strong>Place: </strong><%= p.place %>
				<br>
				<strong>Desc: </strong><%= p.description %>
				<br>
				<strong>Location: </strong><%= p.location %>
				<br>
				<strong>City: </strong><%= p.city %>
				<br> 
    		<strong>Zipcode: </strong><%= p.zipcode %>
				<br>
				<strong>Email: </strong><%= p.email %>
				<br>
				<strong>Tel: </strong><%= p.telephone %>
				<br>
				Posted: <%= time_ago_in_words(p.created_at) %> ago.
				<hr><br>
				<% end %>
				<br>
		</div>
</div>

		

app/views/gymplaces/new.html.erb
<h1>Gymplaces#new</h1>

<%= render 'gymplaceform' %>

app/views/gymplaces/show.html.erb
<h2><%= @gymplace.place%></h2>

<h2>Hi <%= current_user.username %>, please share a review about <%= @gymplace.place %></h2>

<!-- To create a post on this place -->
<%= render 'posts/postform' %>

<!-- The posts on this gymplace from all users  -->
<h3>All reviews for <% @gymplace.place %></h3>

<div class="panel panel-default">
	<div class="panel-heading">All Posts</div>
  <div class="panel-body-post">
  	<% @posts.each do |p| %>
  		<br>
  		<strong>Review: &nbsp;</strong><%= p.post %><br>
  		<strong>User: &nbsp;</strong><%= p.user.username %>	
			<br><hr>
		<% end %>
	</div>
</div>
	<%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: "Newer", next_label: "Older"%>
</div>

app/views/home/about.html.erb
<body class="abbkgrd">
	<div class="gymtalkabout">
		<h1>About <span id="bluelogo">Gym</span><span id="greenlogo">Talk</span></h1>

		<h3 id="end">The social networking app that connects people who want to keep fit, share their fitness experiences, and receive perks

		It is also a marketing tool for any business in the field of providing a health oriented activity that is for people to get fit, keep active, focus on wellness and network with others.</h3>


		<h1>Why <span id="bluelogo">Gym</span><span id="greenlogo">Talk</span></h1>


		<h3 id="end1">Why not replace a part of the time spent looking at a screen or shopping and have a look what is out there to get you moving?</h3>

		<h3 id="end2"> GET MOVING, HAVE FUN, find a gym, take a run, play...be healthy, be smart and live well.</h3>
		

		<div class="contact">
			<h1>Contact Us</h1>
			<h2><span class="email">info@<span id="bluelogo">gym</span><span id="greenlogo">talk</span>.com</span></h2>
		</div>
	</div>
</body>

app/views/home/landing.html.erb
<!-- Applying different background  --> 

<% if current_user %>
<body class="ldbkgrd" >
<% end %>

<!--  menu appears only at login  -->

<% if !current_user %>
    <div id="menu">
      <ul>
         <li><span id="lgn"><%= link_to 'Login', login_path %></span></li>
         <li><span id="sgn"><%= link_to "Sign Up Here!", new_user_path %><span></li>
      </ul>     
    </div>


<!--   landing page for all visitors and members not signed in  -->

<!-- <div class="row"> -->
  <div class="col-xs-12 col-md-8">     
    <div class="home_intro_1">
      <h1 class="wel">Welcome To GymTalk</h1><br>
    </div>
    <div class="home_intro_2">
      <h1 class="wel2">The app for seeking health, networking and who is doing it!</h1><br>
    </div>
  </div>
</div>
</div>


<!-- Appears on login/logout only; bs carousel 3D CSS -->

<div class="goround">
   <!-- <div class="col-xs-6 col-md-4" id="carol"> -->
    <!-- <div class="col-md-6 col-md-offset-3" id="carol"> -->
    <div class="container spin">
        <div id="carousel">
          <figure><img src="../assets/land1.jpg" width="300" height="150" alt=""></figure>
          <figure><img src="../assets/land2.jpg" width="300" height="150" alt=""></figure>
          <figure><img src="../assets/land4.jpg" width="300" height="150" alt=""></figure>
          <figure><img src="../assets/land13.jpg" width="300" height="150" alt=""></figure>
          <figure><img src="../assets/land10.jpg" width="300" height="150" alt=""></figure>
          <figure><img src="../assets/land3.jpg" width="300" height="150" alt=""></figure>
          <figure><img src="../assets/land9.jpg" width="300" height="150" alt=""></figure>
          <figure><img src="../assets/land14.jpg" width="300" height="150" alt=""></figure>
          <figure><img src="../assets/land15.jpg" width="300" height="150" alt=""></figure>
        </div>
     </div>
  <!-- </div> -->
</div>
 
<% end %>


<!--  if user logs in they will have a welcome message on the landing page  and see gym listed-->

<% if current_user %>

<%= render 'partials/navbar' %>


<!-- background image for signed in members landing page-->

<div class="home_container">
    <h2 id="h2"> Welcome <%= current_user.username %>!</h2>
  <div class="home_current_user">
    <h3 id="h2">What are you up to? Looking for a new place to train?
    Look for weekly alerts in GymTalk for discounts, free classes, reduced membership fees, and other updates.</h3><br>
    <div class="thumbnail ads">
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Discount</strong> 1 free class for you and friend at SoulCycle.
      </div>
    </div>
    <div class="thumbnail ads">
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Discount</strong> 1 free class for you and friend at SoulCycle.
      </div>
    </div>
    <div class="thumbnail ads">
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Discount</strong> 1 free class for you and friend at SoulCycle.
      </div>
    </div>
</div>


<!-- Business listing  -->

<div class="row business">
  <div class="col-xs-6 col-md-4">
    <div class="thumbnail" class-"stylepost">
       <div class="panel-heading hdrl">LOCATIONS</div>
        <% @gymplaces.each do |p| %>
        <strong>Place: &nbsp;</strong> <%= link_to p.place, gymplace_path(p) %>
        <strong>Location: &nbsp;</strong> <%= p.description %>
        <strong>Description: &nbsp;</strong> <%= p.location %>
        <strong>City: &nbsp;</strong><%= p.city %><br>
        <strong>Email: &nbsp;</strong><%= p.email %><br>
        <strong>Tel: &nbsp;</strong><%= p.telephone %><br>
        <strong>Posted: &nbsp;</strong><%= time_ago_in_words(p.created_at) %><br>
        <br><hr>
        <% end %>
        <%= will_paginate @gymplaces, renderer: BootstrapPagination::Rails, previous_label: "Newer", next_label: "Older", inner_window: 1, outer_window: 0 %> 
    </div>
   </div>



<!-- User's reviews  -->

  <div class="col-xs-6 col-md-4">
    <div class="thumbnail" class="userp">
       <div class="panel-heading hdrr">REVIEWS</div>
       <% @posts.each do |p| %>
       <%= image_tag p.user.avatar.url(:thumb) %>
        <strong>Place: &nbsp;</strong> <%= p.gymplace.place %> &nbsp; 
        <strong>Location: &nbsp;</strong> <%= p.gymplace.location %>
        <strong>City: &nbsp;</strong><%= p.gymplace.city %><br>
        <strong>Review: &nbsp;</strong><%= p.post %><br>
        <strong>Username: &nbsp;</strong><%= p.user.username %><br>
        <strong>Posted: &nbsp;</strong><%= time_ago_in_words(p.created_at) %><br>
        <br><hr>
        <% end %>        
        <%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: "Newer", next_label: "Older", inner_window: 1, outer_window: 0 %>
      </div> 
    </div>
                     

<!-- Business Gallery -->
<div class="caption"><h2        >Click on images below.</h2></div>
  <div class="container-gallery"> 
    <div class="row">
        <div class="col-xs-6 col-md-3"><a title="Crunch">
            <img class="thumbnail img-responsive" src="../assets/crunch.jpg" width="600" height="300"></a>
            <div class = "caption">
         <h3>CRUNCH</h3>
         <p>Exciting new fitness classes added as requested from Crunch members.</p></div>
          </div>

          <div class="col-xs-6 col-md-3"><a title="Crunch">
            <img class="thumbnail img-responsive" src="../assets/crunch.jpg" width="600" height="300"></a>
            <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p></div>
          </div>

          <div class="col-xs-6 col-md-3"><a title="Crunch">
            <img class="thumbnail img-responsive" src="../assets/crunch.jpg" width="600" height="300"></a>
            <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p></div>
          </div>

          <div class="col-xs-6 col-md-3"><a title="Crunch">
            <img class="thumbnail img-responsive" src="../assets/crunch.jpg" width="600" height="300"></a>
            <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p></div>
          </div>

          <div class="col-xs-6 col-md-3"><a title="Crunch">
            <img class="thumbnail img-responsive" src="../assets/crunch.jpg" width="600" height="300"></a>
            <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p></div>
          </div>

          <div class="col-xs-6 col-md-3"><a title="Crunch">
            <img class="thumbnail img-responsive" src="../assets/crunch.jpg" width="600" height="300"></a>
            <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Some sample text. Some sample text.</p></div>
          </div>


        <!-- <div class="col-xs-6 col-md-3">
          <a title="UFC"><img class="thumbnail img-responsive" src="../assets/ufcgym.jpg"></a></div>

        <div class="col-xs-6 col-md-3"><a title="Blink"><img class="thumbnail img-responsive" src="../assets/blink.jpg" ></a></div>

        <div class="col-xs-6 col-md-3"><a title="Downtown Boathouse NYC"><img class="thumbnail img-responsive" src="../assets/kayak.jpg" width="600" height="300"></a></div>

        <div class="col-xs-6 col-md-3"><a title="SoulCycle"><img class="thumbnail img-responsive" src="../assets/soulcycle.jpg" width="600" height="300"></a></div> -->

        <!-- <div class="col-xs-6 col-md-3"><a title="Bikram Yoga"><img class="thumbnail img-responsive" src="../assets/bikram.jpg" width="600" height="300"></a>
        </div> -->
    </div>
  </div>
</div>
</div>

<div tabindex="-1" class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" type="button" data-dismiss="modal">x</button>
        <h3 class="modal-title">Heading</h3>
      </div>
      <div class="modal-body">
    </div>
    <div class="modal-footer">
      <button class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
   </div>
  </div>
</div> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head> 
  <title>gymtalk</title>
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "new" if controller_name == "new" %>
</head>
<body data-spy="scroll" data-target="#nb">
  
  
<!-- logo -->

  <div class="logo">
    <%= link_to(image_tag("/assets/chat.png", :alt => "logo", :title => "Home"), "/") %><span id="bluelogo">Gym</span><span id="greenlogo">Talk</span>
  </div>



  <!-- insert render to display nav unless marked disabled -->

 <%= render 'partials/navbar' unless @disable_nav %>
 

  
<!--  flash notices  -->

  <div class="flash_n">
    <%= flash[:notice] if flash[:notice] %>
  </div>
  
  <div class="flash_a">
    <%= flash[:alert] if flash[:alert] %>
  </div>


 <!-- yield below  -->

<div id="yield_container">
        <%= yield %>      
</div>



</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
	<ul>
        <li><%= link_to 'Home', root_path, class: "btn btn-success" %></li>    		
    		<% if current_user %>
        <li><%= link_to 'My Profile', current_user, class: "btn btn-success" %></li>
        <li><%= link_to 'GymTalk', posts_path, class: "btn btn-success" %></li>    
            <% end %> 
         <li><%= link_to 'LogOut', logout_path, method: :delete, class: "btn btn-success" %><li>
    </ul>

    <div id="social">
        <li><%= link_to 'About', about_path, class: "btn btn-success" %></li>
        <li><a href="http://www.pininterest.com" alt="pin"><%= image_tag 'pininterest.png' %></a></li>
        <li><a href="http://www.facebook.com" ><%= image_tag 'facebook.png' %></a></li>
        <li><a href="http://www.twitter.com" alt="twitter"><%= image_tag 'twitter.png' %></a></li>
    </div>  
</nav>


      

app/views/posts/_postform.html.erb
<div id="review">
        <div class="form-group">
                <%= form_for [@gymplace,@post]  do |f| %>
                <div class="control-group">  
                        <%= f.label :Post, class: "control-label" %>
                        <%= f.text_area :post, class: "form-control", placeholder: "Tell us about it" %>
                </div><br>
                <div class="control-group">
                        <%=f.label :Picture, class: "control-label" %>
                        <%= f.file_field :avatar, class: "form-control", placeholder: "Upload Photo" %>
                </div><br>
                <div class="form-actions"> 
                        <%= f.submit  'Submit', class: "btn btn-primary" %>
                </div>     
                <% end %>
        </div>
</div>

app/views/posts/create.html.erb
<%= render 'partials/navbar' unless @disable_nav %>

<% if current_user.posts.any? %>
	<h3>Posts (<%= current_user.posts.count %>) </h3>
    <% end %>

    <div>
   		<%= render 'postform' %>
		</div>

app/views/posts/index.html.erb
<%= render 'partials/navbar' unless @disable_nav %>

<h1>Create Review</h1>
<hr><br>

<h1>My Posts</h1>
<% if current_user.posts.any? %>
	<h3>Posts (<%= current_user.posts.count %>)</h3>
<% end %>

<div>
	<%= render 'postform' %>
</div>


<div class="panel panel-default">
    <div class="panel-body-post">
    		<% @posts.each do |r| %>
    		<strong>By: </strong><%= r.user.username %>
    		<br>
    		<strong>Place: </strong><%= r.place %>
				<br>
				<strong>Location: </strong><%= r.location %>
				<br>
				<strong>City: </strong><%= r.city %>
				<br> 
				<strong>Post: </strong><%= r.post %>
				<br>
				Posted: <%= time_ago_in_words(r.created_at) %>.ago.
				<hr><br>
				<% end %>
				<br>
		</div>
</div>

<h5>Your Reviews</h5>
<div class="panel panel-default">
	<div class="panel-body">
	 	<% posts.each do |p| %>
    <%=link_to user do %>
		<strong>Review: </strong><%= p.post %><br>
		<strong>Created: </strong><%= time_go_in_words(p.created_at).ago %>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<body class="nwbkgrd">
<h2>New Review</h2>


<%= render 'postform' %>

</body>

app/views/posts/show.html.erb
 <%#= render 'partials/navbar' unless @disable_nav %>

<h1>Your GymTalk</h1>


<h2>Welcome <%= @user.username %> to GymTalk</h2>


<div class="panel panel-default">
    <div class="panel-body">
    	<% @posts.each do |p| %>
    	<ul>
				<li><%= p.place %></li>
				<li><%= p.location %></li> 
				<li><%= p.city %></li> 
				<li><%= p.post %><li> 
			</ul>
			<% end %>
		</div>
</div>

<%= link_to 'Home', root_path, class: "btn btn-default" %>

app/views/users/edit.html.erb
<h1>Edit Your account</h1>


<%= render 'userform' %>

 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= render 'partials/navbar' unless @disable_nav %>

<h1>GymTalk Members</h1>

<ul>
    <% users.each do |user| %>
        <%=link_to user do %>
          <%= image_tag user.avatar.url(:thumb), class: 'thumbnail'%>
            <h4>user.email</h4>            
            <%= link_to user.username, user.email, user_path(user) %> &nbsp;&nbsp;| 
            <%= link_to "Edit", edit_user_path(user) %>
         <% end %>
     <% end %>   
</ul>

app/views/users/new.html.erb
<body class="nwbkgrd">   
	<h1>Sign Up Here</h1>
	<%= render 'userform' %>  
	<%= link_to 'Back', users_path %>
</body>
    
    
    
 
    
    